// oauth2/react/src/components/NotesPanel.tsx
import { useCallback, useEffect, useState } from 'react';
import { ApiError, api } from '../api/client';
import type { Note, NotesResponse } from '../api/types';
import { useAuth } from '../auth/AuthProvider';

/** The actual "app". Every call below is authorized by the session cookie. */
export function NotesPanel() {
  const { user } = useAuth();
  const [notes, setNotes] = useState<Note[]>([]);
  const [canDeleteAny, setCanDeleteAny] = useState(false);
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const data = await api<NotesResponse>('/api/notes');
      setNotes(data.notes);
      setCanDeleteAny(data.permissions.canDeleteAny);
      setError(null);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const add = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!title.trim()) return;
    try {
      await api('/api/notes', { method: 'POST', body: JSON.stringify({ title, body }) });
      setTitle('');
      setBody('');
      await load();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : String(err));
    }
  };

  const remove = async (id: string) => {
    try {
      await api(`/api/notes/${id}`, { method: 'DELETE' });
      await load();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : String(err));
    }
  };

  const mine = (note: Note) => note.ownerSub === user?.sub;

  return (
    <section className="card">
      <div className="card-head">
        <h2>Notes</h2>
        <button className="ghost" onClick={() => void load()}>Reload</button>
      </div>

      {error && <p className="error">{error}</p>}

      <form className="new-note" onSubmit={add}>
        <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Title" aria-label="Title" />
        <input value={body} onChange={(e) => setBody(e.target.value)} placeholder="Body" aria-label="Body" />
        <button type="submit" className="primary">Add</button>
      </form>

      {loading ? (
        <p className="muted">Loading…</p>
      ) : (
        <ul className="notes">
          {notes.map((note) => (
            <li key={note.id}>
              <div>
                <strong>{note.title}</strong>
                <p>{note.body}</p>
                <span className="muted">
                  {note.ownerName}
                  {mine(note) && ' (you)'} · {new Date(note.createdAt).toLocaleDateString()}
                </span>
              </div>
              <button
                className="danger"
                disabled={!mine(note) && !canDeleteAny}
                title={!mine(note) && !canDeleteAny ? 'Only the owner or an admin can delete this' : 'Delete'}
                onClick={() => void remove(note.id)}
              >
                Delete
              </button>
            </li>
          ))}
        </ul>
      )}
      <p className="muted small">
        Deleting someone else's note requires the <code>admin</code> group. Sign in as <code>bob</code> to see the
        button disabled — and note that the API rejects it too, the UI is only being polite.
      </p>
    </section>
  );
}

// oauth2/angular/src/app/notes-panel.component.ts
import { DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { AuthService } from './auth.service';
import type { Note } from './models';
import { NotesService } from './notes.service';

@Component({
  selector: 'app-notes-panel',
  standalone: true,
  imports: [FormsModule, DatePipe],
  template: `
    <section class="card">
      <div class="card-head">
        <h2>Notes</h2>
        <button class="ghost" (click)="load()">Reload</button>
      </div>

      @if (error(); as message) {
        <p class="error">{{ message }}</p>
      }

      <form class="new-note" (ngSubmit)="add()">
        <input [(ngModel)]="title" name="title" placeholder="Title" aria-label="Title" />
        <input [(ngModel)]="body" name="body" placeholder="Body" aria-label="Body" />
        <button type="submit" class="primary">Add</button>
      </form>

      @if (loading()) {
        <p class="muted">Loading…</p>
      } @else {
        <ul class="notes">
          @for (note of notes(); track note.id) {
            <li>
              <div>
                <strong>{{ note.title }}</strong>
                <p>{{ note.body }}</p>
                <span class="muted">
                  {{ note.ownerName }}@if (mine(note)) { (you) } · {{ note.createdAt | date: 'shortDate' }}
                </span>
              </div>
              <button
                class="danger"
                [disabled]="!mine(note) && !canDeleteAny()"
                [title]="!mine(note) && !canDeleteAny() ? 'Only the owner or an admin can delete this' : 'Delete'"
                (click)="remove(note.id)"
              >
                Delete
              </button>
            </li>
          }
        </ul>
      }

      <p class="muted small">
        Deleting someone else's note requires the <code>admin</code> group. Sign in as <code>bob</code> to see the
        button disabled — and note that the API rejects it too, the UI is only being polite.
      </p>
    </section>
  `,
})
export class NotesPanelComponent {
  private readonly notesService = inject(NotesService);
  private readonly auth = inject(AuthService);

  readonly notes = signal<Note[]>([]);
  readonly canDeleteAny = signal(false);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  title = '';
  body = '';

  constructor() {
    void this.load();
  }

  async load(): Promise<void> {
    this.loading.set(true);
    try {
      const data = await firstValueFrom(this.notesService.list());
      this.notes.set(data.notes);
      this.canDeleteAny.set(data.permissions.canDeleteAny);
      this.error.set(null);
    } catch (err) {
      this.error.set(describe(err));
    } finally {
      this.loading.set(false);
    }
  }

  async add(): Promise<void> {
    if (!this.title.trim()) return;
    try {
      await firstValueFrom(this.notesService.create(this.title, this.body));
      this.title = '';
      this.body = '';
      await this.load();
    } catch (err) {
      this.error.set(describe(err));
    }
  }

  async remove(id: string): Promise<void> {
    try {
      await firstValueFrom(this.notesService.remove(id));
      await this.load();
    } catch (err) {
      this.error.set(describe(err));
    }
  }

  mine(note: Note): boolean {
    return note.ownerSub === this.auth.user()?.sub;
  }
}

function describe(err: unknown): string {
  if (err instanceof HttpErrorResponse) return err.error?.message ?? err.message;
  return String(err);
}
