// oauth2/react/src/components/SessionPanel.tsx
import { useEffect, useState } from 'react';
import { useAuth } from '../auth/AuthProvider';

/** Shows what the backend knows about the session. Purely educational. */
export function SessionPanel() {
  const { session, config, forceRefresh, reload } = useAuth();
  const [busy, setBusy] = useState(false);
  const [countdown, setCountdown] = useState(session?.token.expiresInSeconds ?? 0);

  useEffect(() => {
    setCountdown(session?.token.expiresInSeconds ?? 0);
    const id = setInterval(() => setCountdown((c) => Math.max(0, c - 1)), 1000);
    return () => clearInterval(id);
  }, [session]);

  if (!session) return null;

  return (
    <section className="card">
      <h2>Session</h2>
      <dl className="kv">
        <dt>Authenticated via</dt>
        <dd><code>{session.via}</code> cookie (no token in JavaScript)</dd>
        <dt>Identity provider</dt>
        <dd><code>{config?.authMode === 'mock' ? 'mock IdP' : 'AWS Cognito'}</code></dd>
        <dt>Issuer</dt>
        <dd className="mono-wrap">{session.token.issuer}</dd>
        <dt>Groups</dt>
        <dd>{session.user.groups.length ? session.user.groups.map((g) => <span key={g} className="chip">{g}</span>) : <em>none</em>}</dd>
        <dt>Access token expires</dt>
        <dd>
          in <strong>{countdown}s</strong>
          {countdown === 0 && <em> — the next API call renews it automatically</em>}
        </dd>
        {session.token.refreshedAt && (
          <>
            <dt>Last refreshed</dt>
            <dd>{new Date(session.token.refreshedAt).toLocaleTimeString()}</dd>
          </>
        )}
      </dl>
      <div className="row">
        <button
          className="ghost"
          disabled={busy}
          onClick={async () => {
            setBusy(true);
            try {
              await forceRefresh();
            } finally {
              setBusy(false);
            }
          }}
        >
          Force token refresh
        </button>
        <button className="ghost" onClick={() => void reload()}>Re-check session</button>
      </div>
    </section>
  );
}

// oauth2/angular/src/app/session-panel.component.ts
import { DatePipe } from '@angular/common';
import { Component, effect, inject, signal } from '@angular/core';
import { AuthService } from './auth.service';

@Component({
  selector: 'app-session-panel',
  standalone: true,
  template: `
    @if (auth.session(); as session) {
      <section class="card">
        <h2>Session</h2>
        <dl class="kv">
          <dt>Authenticated via</dt>
          <dd><code>{{ session.via }}</code> cookie (no token in JavaScript)</dd>
          <dt>Identity provider</dt>
          <dd><code>{{ auth.config()?.authMode === 'mock' ? 'mock IdP' : 'AWS Cognito' }}</code></dd>
          <dt>Issuer</dt>
          <dd class="mono-wrap">{{ session.token.issuer }}</dd>
          <dt>Groups</dt>
          <dd>
            @for (group of session.user.groups; track group) {
              <span class="chip">{{ group }}</span>
            } @empty {
              <em>none</em>
            }
          </dd>
          <dt>Access token expires</dt>
          <dd>
            in <strong>{{ countdown() }}s</strong>
            @if (countdown() === 0) {
              <em> — the next API call renews it automatically</em>
            }
          </dd>
          @if (session.token.refreshedAt) {
            <dt>Last refreshed</dt>
            <dd>{{ session.token.refreshedAt | date: 'mediumTime' }}</dd>
          }
        </dl>
        <div class="row">
          <button class="ghost" [disabled]="busy()" (click)="refresh()">Force token refresh</button>
          <button class="ghost" (click)="auth.reload()">Re-check session</button>
        </div>
      </section>
    }
  `,
  imports: [DatePipe],
})
export class SessionPanelComponent {
  readonly auth = inject(AuthService);
  readonly busy = signal(false);
  readonly countdown = signal(0);

  constructor() {
    effect(() => this.countdown.set(this.auth.session()?.token.expiresInSeconds ?? 0));
    setInterval(() => this.countdown.update((c) => Math.max(0, c - 1)), 1000);
  }

  async refresh(): Promise<void> {
    this.busy.set(true);
    try {
      await this.auth.forceRefresh();
    } finally {
      this.busy.set(false);
    }
  }
}
